### ISSUE TITLE
Can Support Redis Vector Search？

### ISSUE THREAD

**Issue by geffzhang** [tombatron/RediSearchClient#17]
Hi
I would like to know ,does RediSearchClient support vector search?

 https://redis.com/blog/rediscover-redis-for-vector-similarity-search/

**Comment by tombatron** [comment]
So I've done some work to add vector support. 

https://www.nuget.org/packages/RediSearchClient/2.1.0-beta

I still need to get the documentation in order, but there are some examples in the integration tests.

**Comment by tombatron** [comment]
I'm going to go ahead and close this, since the vector support is out there.
